export enum VISIBILITY {
  PUBLIC = 'PUBLIC',
  FOLLOWERS = 'FOLLOWERS',
  FRIENDS = 'FRIENDS',
  ONLY_ME = 'ONLY_ME',
}
export enum EntityType {
  POST = 'POST',
  CHALLENGE = 'CHALLENGE',
  STORY='STORY'
}